
from langchain.tools import tool
from langchain.agents import create_agent
from langchain_ollama import ChatOllama
import requests
from pydantic import BaseModel, Field

model = ChatOllama(
    model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
    base_url='http://localhost:11434',
    system="Respond only with a horoscope generated by a tool."
)

@tool
def get_user_details(user_id):
    """Get user details for a given user ID.
    Args:
    user_id (str): The ID of the user to fetch details for.
    Returns:
    dict: A dictionary containing user details such as name, age, and astrological sign.

    """
    print(f"Fetching user details for user_id: {user_id} using tool...")
    # Simulate fetching user details from a database or external API
    user_details = {
        "user_id": user_id,
        "name": "John Doe",
        "age": 30,
        "astrological_sign": "Aquarius"
    }
    return user_details

@tool
def get_horoscope(sign):
    """
    Get today's horoscope for an astrological sign.

    Args:
        sign (str): The astrological sign to get the horoscope for.
        
    Returns:
        str: The horoscope for the given astrological sign.
    """
    print(f"Fetching horoscope for {sign} using tool...")
    url = f"https://www.freehoroscopeapi.com/api/v1/get-horoscope/daily?sign={sign.lower()}"
    try:
        # WARNING: Disabling SSL verification is insecure and should only be used for testing.
        response = requests.get(url, timeout=10, verify=False)
        response.raise_for_status()
        data = response.json()
        return data.get("data", {}).get("horoscope", "No horoscope found.")
    except Exception as e:
        print(f"Error fetching horoscope for {sign}: {e}")
        return f"{sign.capitalize()}: Error fetching horoscope. ({e})"
    
@tool
def update_horoscope_for_user(user_id, horoscope):
    """ Update the user's horoscope in the database.
    Args:
    user_id (str): The ID of the user to update the horoscope for.
    horoscope (str): The horoscope to update for the user.
    Returns:
    str: A confirmation message indicating the horoscope has been updated for the user.
    """
    print(f"Updating horoscope for user_id: {user_id} with horoscope: {horoscope} using tool...")
    # Simulate updating the user's horoscope in a database
    return f"Horoscope for user_id {user_id} updated to: {horoscope}"

# Get Country of user
# Country Capital
# Country State
# Country State Capital
# Country Population

agent = create_agent(
    model=model,
    tools=[get_horoscope, get_user_details, update_horoscope_for_user],
    # debug = True
)

messages = [
    {"role":"system", "content": "You are a personal assistant. " 
    "When the user provides their user ID Do you will fetch their details using get_user_details tool, get their astrological sign returned by get_user_details tool, fetch their horoscope for the day using get_horoscope tool, and update the horoscope fetched by get_horoscope tool in the database using update_horoscope_for_user tool. " 
    "Use the provided tools to perform these actions. Always respond with the final horoscope update confirmation."},
    {"role": "user", "content": "My user ID is 123."}
]

ai_msg = agent.invoke({"messages": messages})

for i in range(len(ai_msg.get("messages"))):
    print(ai_msg.get('messages')[i])
    print("\n\n")