from langchain.tools import tool
from langchain_ollama import ChatOllama

model = ChatOllama(
    model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
    base_url='http://localhost:11434',
    system="Respond only with a horoscope generated by a tool."
)

@tool
def get_weather(city):
    """Simple HTTP call to a public weather service
    
    Args:
        city (str): The city to get the weather for.
        
    Returns:
        str: The weather for the given city.
    """
    return f"{city}: +12°C"

model_with_tools = model.bind_tools([get_weather])

def run_agent(user_message):
    messages = [
        {"role": "user", "content": user_message}
    ]
    print("— Asking Ollama...")
    ai_msg = model_with_tools.invoke(messages)
    messages.append(ai_msg)
    # Step 2: Execute tools and collect results
    # Execute the tool with the generated arguments
    for tool_call in ai_msg.tool_calls:
        if tool_call.get("name") == "get_weather":
            print(f"— Tool Call Triggered for: {tool_call['args']}")
            tool_result = get_weather.invoke(tool_call)
            print(f"— Real API Result: {tool_result.content}")
            messages.append(tool_result)
    print("\n— Sending results back to Ollama for final answer...")

    # Step 3: Pass results back to model for final response
    ai_msg = model_with_tools.invoke(messages)
    return ai_msg.text

if __name__ == "__main__":
    user_question = "What's the weather in Bogotá, Colombia in celsius?"
    print(f"User: {user_question}\n")
    answer = run_agent(user_question)
    print(f"Agent: {answer}")

