
### Using langchain agents with single tool

from langchain.tools import tool
from langchain.agents import create_agent
from langchain_ollama import ChatOllama

model = ChatOllama(
    model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
    base_url='http://localhost:11434',
    system="Respond only with a horoscope generated by a tool."
)

@tool
def get_weather(city):
    """Simple HTTP call to a public weather service
    
    Args:
        city (str): The city to get the weather for.
        
    Returns:
        str: The weather for the given city.
    """
    print(f"— Tool Call Triggered for: {city}")
    result = f"{city}: +12°C"
    print(f"— Real API Result: {result}")
    return result

agent = create_agent(
    model=model,
    tools=[get_weather],
    # debug=True
)

def run_agent(user_message):
    messages = [
        {"role": "user", "content": user_message}
    ]
    print("— Asking Ollama...")
    ai_msg = agent.invoke({"messages": messages})

    return ai_msg.get("messages")[-1].content

if __name__ == "__main__":
    user_question = "What's the weather in Bogotá, Colombia in celsius?"
    print(f"User: {user_question}\n")
    answer = run_agent(user_question)
    print(f"Agent: {answer}")
