

from openai import OpenAI
import json

# Initialize client pointing to local Ollama with OpenAI-compatible endpoint
client = OpenAI(
    base_url='http://localhost:11434/v1',
    api_key='ollama'  # Required but can be anything for local Ollama
)

# Define available tools
tools = [
        {
        "type": "function",
        "name": "get_weather",
        "description": "Get current weather for a location.",
        "parameters": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "description": "City and country, e.g., 'Bogotá, Colombia'"
                }
            },
            "required": ["city"],
        },
    }

]

def get_weather(city):
    """Simple HTTP call to a public weather service"""
    return f"{city}: +12°C"

def run_agent(user_message):
    """Run an agent loop: LLM decides if tool is needed, execute tool, get final answer."""
    input_list = [
        {"role": "user", "content": user_message}
    ]
    print("— Step 1 : Ask Assistant about user query ...")
    # 2. Prompt the model with tools defined
    response = client.responses.create(
        model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
        tools=tools,
        input=input_list,
    )

    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_weather":
                # 3. Execute the function logic for get_weather
                args = json.loads(item.arguments)
                city = args.get("city")
                print(f"— Step 2 : Tool Call Triggered for getting weather")
                weather = get_weather(city)
                print(f"— Step 3 : Got weather info from tool")
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "weather": weather
                    })
                })
    print(f"— Step 4 : Assistant processing tool response...")
    response = client.responses.create(
        model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
        instructions="Respond only with the weather information generated by a tool.",
        tools=tools,
        input=input_list,
    )
    return response.output_text

if __name__ == "__main__":
    user_question = "What's the weather in Bogotá, Colombia in celsius?"
    print(f"User: {user_question}")
    answer = run_agent(user_question)
    print(f"Assistant : {answer}")


