

from openai import OpenAI
import json
import requests

# Initialize client pointing to local Ollama with OpenAI-compatible endpoint
client = OpenAI(
    base_url='http://localhost:11434/v1',
    api_key='ollama'  # Required but can be anything for local Ollama
)

# Define available tools
tools = [
    {
        "type": "function",
        "name": "get_pincode",
        "description": "Get the pincode for a city.",
        "parameters": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "description": "City name, e.g., 'Bogotá, Colombia'",
                },
            },
            "required": ["city"],
        },
    },
    {
        "type": "function",
        "name": "get_weather",
        "description": "Get current weather for a location.",
        "parameters": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "description": "City and country, e.g., 'Bogotá, Colombia'"
                }
            },
            "required": ["city"],
        },
    }
]

def get_pincode(city):
    """Simple HTTP call to a public pincode service"""
    return f"{city}: 123456"

def get_weather(city):
    """Simple HTTP call to a public weather service"""
    return f"{city}: +12°C"

def run_agent(user_message):
    """Run an agent loop: LLM decides if tool is needed, execute tool, get final answer."""
    input_list = [
        {"role": "user", "content": user_message}
    ]
    print("— Step 1 : Asking Assistant about user query ...")
    # 2. Prompt the model with tools defined
    response = client.responses.create(
        model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
        tools=tools,
        input=input_list,
    )

    # Save function call outputs for subsequent requests
    input_list += response.output

    for item in response.output:
        if item.type == "function_call":
            if item.name == "get_weather":
                # 3. Execute the function logic for get_weather
                args = json.loads(item.arguments)
                city = args.get("city")
                print(f"— Step 2 : Tool Call Triggered for getting weather")
                weather = get_weather(city)
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "weather": weather
                    })
                })
            elif item.name == "get_pincode":
                # 3. Execute the function logic for get_pincode
                args = json.loads(item.arguments)
                city = args.get("city")
                print(f"— Step 2 : Tool Call Triggered for getting pincode")
                pincode = get_pincode(city)                
                # 4. Provide function call results to the model
                input_list.append({
                    "type": "function_call_output",
                    "call_id": item.call_id,
                    "output": json.dumps({
                    "pincode": pincode
                    })
                })
    print(f"— Step 3 : Got tool responses, now Assistant processing the response for final answer...")
    response = client.responses.create(
        model="llama3.1:latest",  # Note: or "lfm2.5-thinking:latest" for better reasoning
        instructions="Respond only with the weather information generated by a tool.",
        tools=tools,
        input=input_list,
    )
    return response.output_text

if __name__ == "__main__":
    user_question = "What is the weather in Berlin?"
    print(f"User: {user_question}\n")
    answer = run_agent(user_question)
    print(f"Assistant : {answer}")
    print("="*60)
    user_question = "What is the pincode of Berlin?"
    print(f"User: {user_question}\n")
    answer = run_agent(user_question)
    print(f"Assistant : {answer}")



